ALTER TABLE settings ADD COLUMN IF NOT EXISTS gdrive_refresh_token TEXT NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS gdrive_folder_id VARCHAR(100) NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS gdrive_account VARCHAR(190) NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS gdrive_last_upload_at DATETIME NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS gdrive_last_error VARCHAR(255) NULL;
