ALTER TABLE advertisements ADD COLUMN IF NOT EXISTS badge VARCHAR(20) NULL AFTER link_url;
ALTER TABLE advertisements ADD COLUMN IF NOT EXISTS phone VARCHAR(30) NULL AFTER badge;
ALTER TABLE advertisements ADD COLUMN IF NOT EXISTS map_url VARCHAR(255) NULL AFTER phone;
ALTER TABLE advertisements ADD COLUMN IF NOT EXISTS line_url VARCHAR(255) NULL AFTER map_url;
ALTER TABLE advertisements ADD COLUMN IF NOT EXISTS vendor_id INT UNSIGNED NULL AFTER line_url;
