ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(32) NULL;
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS totp_enabled TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS totp_backup_codes TEXT NULL;
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS checkin_link_token_hash VARCHAR(64) NULL;
